networks:
  mynetwork:
    driver: bridge

services:
  financialchat.api.web:
    image: financialchatwebapi
    container_name: financialchat.api.web
    build:
      context: .
      dockerfile: ./FinancialChat.API/Dockerfile
    ports:
      - "5100:8080"
    networks:
      - mynetwork

  financialchat.ui.web:
    image: financialchatuiweb
    container_name: financialChat.ui.web
    build:
      context: ./FinancialChat.UI
    ports:
      - "3000:8080"
    volumes:
      - ./FinancialChat.UI:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

  financialchat.reverse.proxy:
    image: financialchat.reverse.proxy
    container_name: financialchat.reverse.proxy
    build:
      context: .
      dockerfile: ./FinancialChat.Infra/NGINX/Dockerfile
    ports:
      - "10000:80"
    depends_on:
      - "financialchat.api.web"
      - "financialchat.ui.web"
    networks:
      - mynetwork

volumes:
  dbdata6: