networks:
  mynetwork:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: dbPostgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  financialchat.api.web:
    image: financialchatwebapi
    container_name: financialchat.api.web
    build:
      context: .
      dockerfile: ./FinancialChat.API/Dockerfile
    depends_on:
      - db
    ports:
      - "5100:8080"
    networks:
      - mynetwork

  financialchat.ui.web:
    image: financialchatuiweb
    container_name: financialChat.ui.web
    build:
      context: ./FinancialChat.UI
    ports:
      - "3000:8080"
    volumes:
      - ./FinancialChat.UI:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

  financialchat.reverse.proxy:
    image: financialchat.reverse.proxy
    container_name: financialchat.reverse.proxy
    build:
      context: .
      dockerfile: ./FinancialChat.Infra/NGINX/Dockerfile
    ports:
      - "10000:80"
    depends_on:
      - "financialchat.api.web"
      - "financialchat.ui.web"
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - mynetwork

volumes:
  db:
    driver: local